name: Main

on:
  pull_request:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build-stylable-types
      - uses: actions/cache/save@v3
        id: npm-cache
        with:
          path: |
            ~/.npm
            node_modules
            st_types
          key: node-cache-${{ hashFiles('**/package-lock.json') }}

  lint:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache/restore@v3
        id: npm-cache
        with:
          path: |
            ~/.npm
            node_modules
            st-types
          key: |
            node-cache-${{ hashFiles('**/package-lock.json') }}
            node-cache-
      - run: npm run lint

  # typecheck:
  #   runs-on: ubuntu-latest
  #   needs: setup
  #   strategy:
  #     matrix:
  #       node-version: [14.x, 16.x, 18.x]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #     - uses: actions/cache/save@v3
  #       id: npm-cache
  #       with:
  #         path: |
  #           ~/.npm
  #           node_modules
  #           st_types
  #         key: ${{ matrix.node-version }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
  #     - run: npm run typecheck

  # unit-tests:
  #   runs-on: ubuntu-latest
  #   needs: [lint, typecheck]
  #   strategy:
  #     matrix:
  #       node-version: [14.x, 16.x, 18.x]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #     - uses: actions/cache/save@v3
  #       id: npm-cache
  #       with:
  #         path: |
  #           ~/.npm
  #           node_modules
  #           st_types
  #         key: ${{ matrix.node-version }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
  #     - run: npm run unit-tests

  # cypress-component-tests:
  #   runs-on: ubuntu-latest
  #   needs: [lint, typecheck]
  #   strategy:
  #     matrix:
  #       node-version: [14.x, 16.x, 18.x]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #     - uses: actions/cache/save@v3
  #       id: npm-cache
  #       with:
  #         path: |
  #           ~/.npm
  #           node_modules
  #           st_types
  #         key: ${{ matrix.node-version }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
  #     - run: npm run cypress run --component
